kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traefik-proxy-internal
  labels:
    app: traefik-proxy-internal
    tier: proxy
spec:
  selector:
    matchLabels:
      app: traefik-proxy-internal
      tier: proxy
  template:
    metadata:
      labels:
        app: traefik-proxy-internal
        tier: proxy
    spec:
      serviceAccountName: traefik-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: config
        configMap:
          name: traefik-internal
      containers:
      - image: traefik:1.7.9
        name: traefik-proxy-internal
        volumeMounts:
        - mountPath: /config
          name: config
        resources:
          requests:
            cpu: 100m
            memory: 50M
        ports:
        - containerPort: 80
          name: traefik-http
        - containerPort: 8080
          name: traefik-ui
        - containerPort: 443
          name: traefik-https
        args:
        - --configfile=/config/traefik-internal.toml
        - --logLevel=INFO
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: traefik-ingress-controller-scaler-internal
spec:
  scaleTargetRef:
    apiVersion: extensions/v1beta1 
    kind: Deployment
    name: traefik-proxy-internal
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 85
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-proxy-internal
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  selector:
    app: traefik-proxy-internal
    tier: proxy
  ports:
  - port: 80
    name: http
    targetPort: 80
  - port: 443
    name: https
    targetPort: 443
